### ISSUE TITLE
XML fails to validate to the OSIS schema

### ISSUE THREAD

**Issue by DavidHaslam** [lemtom/coverdale#15]
Further to your commit on 4 February 2018, the XML file fails to validate (though it passes XML syntax check).

The problems are all related to the use of the **l** element used to mark the word `Sela.` 
```
<l type="selah">Sela.</l>
```
This may only be used within the OSIS **line group** element `<lg>...</lg>`.

[coverdale.xml.validation.log](https://github.com/lemtom/coverdale/files/1698960/coverdale.xml.validation.log)

**Comment by lemtom** [comment]
Ah, yes, I understand now. I will remove the l element for now, since the scans just have the psalms as regular text, no different formatting.
